return {
	{
		"nvim-treesitter/nvim-treesitter",
		build = ":TSUpdate",
		main = "nvim-treesitter.configs",
		opts = {
			ensure_installed = {
				"bash",
				"diff",
				"html",
				"javascript",
				"json",
				"lua",
				"python",
				"tsx",
				"typescript",
				"vim",
				"yaml",
				"rust",
				"go",
				"sql",
				"java",
				"kotlin",
				"groovy",
				"ruby",
				"embedded_template",
			},
			auto_install = true,
			highlight = {
				enable = true,
				additional_vim_regex_highlighting = { "ruby" },
			},
			indent = { enable = true, disable = { "ruby" } },
		},
	},
}
